color: blue
fieldLayouts:
  e4f706ff-ff32-4345-bc8a-901b2dd8d25d:
    cardView:
      - dateUpdated
      - uid
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-17T12:41:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 532e8950-8267-4d68-9848-63e2fa871416
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T12:42:52+00:00'
            elementCondition: null
            fieldUid: 8a80f2d2-f9ab-4c14-94ca-89414b5d6d60 # Content Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b2c6dad-9a92-4bc8-be51-f51126de3340
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b628d26c-d6fd-4046-9558-f1d38368b426
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-17T14:53:10+00:00'
            elementCondition: null
            fieldUid: 0e946fe4-fea0-467e-a36c-a71a36941462 # Seo Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a506ae43-92bd-4723-a6e0-51f20b17903a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e42aef8c-cbb3-4f27-bb5a-d84f8c836cdc
        userCondition: null
handle: pageLayout
hasTitleField: true
icon: file
name: 'Page Layout'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
