defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6b082bd3-deb7-4f0c-8d54-e68f443ad399 # Page Layout
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  17f7ea10-56cf-43e0-81f1-240a6ef0c952: # boilertemplate-nuxt-craftcms
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
