columnSuffix: null
handle: cta
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - target
    - title
    - class
    - ariaLabel
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - '1'
  types:
    - entry
    - url
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
