columnSuffix: null
handle: navigation
instructions: null
name: Navigation
searchable: false
settings:
  createButtonLabel: 'Add Navigation Links'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 1f27e61f-7bad-445f-b2fe-e70d009bf943 # Navigation List
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
